name: SonarQube analyze

on:
  push:
    branches: [ main ]

jobs:

  # This workflow contains a single job called "build"
  build:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/api/target
          key: mvn-${{ hashFiles('pom.xml') }}
          restore-keys: mvn-

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
        working-directory: ~/api

      - name: Build with Maven
        run: mvn clean verify sonar:sonar \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.host.url=https://sonarcloud.io            
        working-directory: ~/api
